### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by liushifu12138** [JiayuYANG/CVP-MVSNet#30]
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    train()
  File "train.py", line 137, in train
    loss = train_sample(sample, detailed_summary=do_summary)
  File "train.py", line 183, in train_sample
    loss.append(model_loss(depth_est_list[i], depth_gt.float(), mask))
  File "/mnt/CVP-MVSNet-master/CVP_MVSNet/models/net.py", line 195, in sL1_loss
    return F.smooth_l1_loss(depth_est[mask], depth_gt[mask], reduction='mean')
IndexError: The shape of the mask [1, 128, 160] at index 1 does not match the shape of the indexed tensor [1, 512, 640] at index 1

**Comment by JiayuYANG** [comment]
Hi liushifu12138,

Are you using the training dataset provided by MVSNet?
The training set provided by MVSNet is different from the one I provide, since MVSNet and CVP-MVSNet have different structure.
MVSNet take 512x640 image in and estimate depth map of 128x160 size.
CVP-MVSNet take 128x160 image in and estimate depth map of the same resolution.

Cheers,
Jiayu.

**Comment by liushifu12138** [comment]
How to test on tank data set？
Can you share your code？please

**Comment by wln19** [comment]
hello , can you test on tank data
